import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResizableSidebarLayout from "@/components/layout/ResizableSidebarLayout";
import { cn } from "@/utils/cn";
import SidebarNav from "@/components/layout/SidebarNav";
import { ViewportProvider } from "@/components/layout/ViewportContext";
import { LocatorInit } from "@/components/LocatorInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased")}>
        <LocatorInit />
        <ViewportProvider>
          <ResizableSidebarLayout sidebar={<SidebarNav />}>
            {children}
          </ResizableSidebarLayout>
        </ViewportProvider>
      </body>
    </html>
  );
}
