import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import ResizableSidebarLayout from "@/components/layout/ResizableSidebarLayout";
import { cn } from "@/utils/cn";
import SidebarNav from "@/components/layout/SidebarNav";
import { ViewportProvider } from "@/components/layout/ViewportContext";
import { AgGridRegistry } from "@/components/AgGridRegistry";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("font-sans antialiased")}>
        <AgGridRegistry />
        <ViewportProvider>
          <ResizableSidebarLayout sidebar={<Suspense fallback={null}><SidebarNav /></Suspense>}>
            {children}
          </ResizableSidebarLayout>
        </ViewportProvider>
        <Analytics />
      </body>
    </html>
  );
}
